name: Hackney.Core.Authorization-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Authorization/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.Authorization/**"
      - ".github/workflows/Hackney.Core.Authorization.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Authorization
      package_name: Hackney.Core.Authorization
      publish_dir: Hackney.Core/Hackney.Core.Authorization/bin/Release
      docker_service: hackney-core-authorization-test
      format_root: Hackney.Core
      skip_tests: false
