name: Hackney.Core.ElasticSearch-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - major/**
      - minor/**
      - patch/**
    paths:
      - "Hackney.Core/Hackney.Core.ElasticSearch/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.ElasticSearch/**"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.ElasticSearch
      package_name: Hackney.Core.ElasticSearch
      publish_dir: Hackney.Core/Hackney.Core.ElasticSearch/bin/Release
      docker_service: hackney-core-elasticsearch-test
      format_root: Hackney.Core
      skip_tests: false
