name: Hackney.Core.Testing.ElasticSearch-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.ElasticSearch/**"
      - ".github/workflows/Hackney.Core.Testing.ElasticSearch.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Core/Hackney.Core.Testing
      pack_project: Hackney.Core.Testing.ElasticSearch
      package_name: Hackney.Core.Testing.ElasticSearch
      publish_dir: Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.ElasticSearch/bin/Release
      docker_service: ""
      format_root: Hackney.Core/Hackney.Core.Testing
      skip_tests: true
