name: Hackney.Core.Validation-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Validation/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.Validation/**"
      - ".github/workflows/Hackney.Core.Validation.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml

    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Validation
      package_name: Hackney.Core.Validation
      publish_dir: Hackney.Core/Hackney.Core.Validation/bin/Release
      docker_service: hackney-core-validation-test
      format_root: Hackney.Core
      skip_tests: false
