name: Hackney.Core.Enums-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - major/**
      - minor/**
      - patch/**
    paths:
      - "Hackney.Core/Hackney.Core.Enums/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.Enums/**"
      - ".github/workflows/Hackney.Core.Enums.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Enums
      package_name: Hackney.Core.Enums
      publish_dir: Hackney.Core/Hackney.Core.Enums/bin/Release
      docker_service: hackney-core-enums-test
      format_root: Hackney.Core
      skip_tests: false
