name: Hackney.Core.Validation.AspNet-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Validation.AspNet/**"
      - "Hackney.Core.Tests.Validation.AspNet/**"
      - ".github/workflows/Hackney.Core.Validation.AspNet.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml

    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Validation.AspNet
      package_name: Hackney.Core.Validation.AspNet
      publish_dir: Hackney.Core/Hackney.Core.Validation.AspNet/bin/Release
      docker_service: hackney-core-validation-aspnet-test
      format_root: Hackney.Core
      skip_tests: false
