name: Hackney.Core.DynamoDb-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.DynamoDb/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.DynamoDb/**"
      - ".github/workflows/Hackney.Core.DynamoDb.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml

    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.DynamoDb
      package_name: Hackney.Core.DynamoDb
      publish_dir: Hackney.Core/Hackney.Core.DynamoDb/bin/Release
      docker_service: hackney-core-dynamodb-test
      format_root: Hackney.Core
      skip_tests: false
