name: Hackney.Core.Http-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Http/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.Http/**"
      - ".github/workflows/Hackney.Core.Http.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml

    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Http
      package_name: Hackney.Core.Http
      publish_dir: Hackney.Core/Hackney.Core.Http/bin/Release
      docker_service: hackney-core-http-test
      format_root: Hackney.Core
      skip_tests: false
