name: Hackney.Core.Logging-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - major/**
      - minor/**
      - patch/**
    paths:
      - "Hackney.Core/Hackney.Core.Logging/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.Logging/**"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Logging
      package_name: Hackney.Core.Logging
      publish_dir: Hackney.Core/Hackney.Core.Logging/bin/Release
      docker_service: hackney-core-logging-test
      format_root: Hackney.Core
      skip_tests: false
