name: Hackney.Core.Middleware-publish
on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Middleware/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.Middleware/**"
      - ".github/workflows/Hackney.Core.Middleware.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.Middleware
      package_name: Hackney.Core.Middleware
      publish_dir: Hackney.Core/Hackney.Core.Middleware/bin/Release
      docker_service: hackney-core-middleware-test
      format_root: Hackney.Core
      skip_tests: false
