name: Hackney.Core.Testing.Shared-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.Shared/**"
      - ".github/workflows/Hackney.Core.Testing.Shared.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml

    with:
      project_root: Hackney.Core/Hackney.Core.Testing
      pack_project: Hackney.Core.Testing.Shared
      package_name: Hackney.Core.Testing.Shared
      publish_dir: Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.Shared/bin/Release
      docker_service: ""
      format_root: Hackney.Core/Hackney.Core.Testing
      skip_tests: true
