name: Hackney.Core.Testing.PactBroker-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - major/**
      - minor/**
      - patch/**
    paths:
      - "Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.PactBroker/**"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Core/Hackney.Core.Testing
      pack_project: Hackney.Core.Testing.PactBroker
      package_name: Hackney.Core.Testing.PactBroker
      publish_dir: Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.PactBroker/bin/Release
      docker_service: ""
      format_root: Hackney.Core/Hackney.Core.Testing
      skip_tests: true
