name: Hackney.Core.JWT-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.JWT/**"
      - "Hackney.Core.Tests/Hackney.Core.Tests.JWT/**"
      - ".github/workflows/Hackney.Core.JWT.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    with:
      project_root: Hackney.Core
      pack_project: Hackney.Core.JWT
      package_name: Hackney.Core.JWT
      publish_dir: Hackney.Core/Hackney.Core.JWT/bin/Release
      docker_service: hackney-core-jwt-test
      format_root: Hackney.Core
      skip_tests: false
