name: Hackney.Shared.Strings-publish
on:
  push:
    branches:
      - release
      - feature/**
      - AddedSolutionFile
    paths:
      - "Hackney.Shared/Hackney.Shared.Strings/**"
      - ".github/workflows/Hackney.Shared.Strings.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_root: Hackney.Shared
      pack_project: Hackney.Shared.Strings
      package_name: Hackney.Shared.Strings
      publish_dir: Hackney.Shared/Hackney.Shared.Strings/bin/Release
      docker_service: ""
      format_root: Hackney.Shared
      skip_tests: true
