name: Hackney.Core.Testing.Sns-publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - release
      - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.Sns/**"
      - ".github/workflows/Hackney.Core.Testing.Sns.yml"

jobs:
  call:
    uses: ./.github/workflows/reusable-publish.yml

    with:
      project_root: Hackney.Core/Hackney.Core.Testing
      pack_project: Hackney.Core.Testing.Sns
      package_name: Hackney.Core.Testing.Sns
      publish_dir: Hackney.Core/Hackney.Core.Testing/Hackney.Core.Testing.Sns/bin/Release
      docker_service: ""
      format_root: Hackney.Core/Hackney.Core.Testing
      skip_tests: true
